platform :ios, '8.0'
target 'JZDjMusicMainProject' do
    pod 'IQKeyboardManager'
    pod 'YYKit'
    pod 'MJRefresh'
    pod 'ChameleonFramework'
    pod 'MJExtension'
    pod 'AvoidCrash'
    pod 'FMDB'
    pod 'SDWebImage'
    pod 'SVProgressHUD'
    pod 'LYEmptyView'
    pod 'FreeStreamer'
end


